---
# Base directory configuration
tools_owner: "{{ lookup('env', 'USER') }}"
#tools_disk_name: "ext4"
tools_basedir: "/home/wgn/WORKING"
progsativos_dir: "{{ tools_basedir }}/Progsativos"
ides_base_dir: "{{ progsativos_dir }}/ides"
db_tools_base_dir: "{{ progsativos_dir }}/db_tools"

# IDE Specific Paths
intellij_dir: "{{ ides_base_dir }}/intellij-ides/intellij"
pycharm_dir: "{{ ides_base_dir }}/pycharm-ides/pycharm"
webstorm_dir: "{{ ides_base_dir }}/webstorm-ides/webstorm"
vscode_dir: "{{ ides_base_dir }}/vscode"
antigravity_dir: "{{ ides_base_dir }}/antigravity"
cursor_dir: "{{ ides_base_dir }}/cursor"

# DB Tools Specific Paths
dbeaver_dir: "{{ db_tools_base_dir }}/dbeaver"
datagrip_dir: "{{ db_tools_base_dir }}/datagrip"

# Download URLs
intellij_url: "https://download.jetbrains.com/idea/ideaIC-2024.1.1.tar.gz"
pycharm_url: "https://download.jetbrains.com/python/pycharm-community-2024.1.1.tar.gz"
webstorm_url: "https://download.jetbrains.com/webstorm/WebStorm-2024.1.1.tar.gz"
vscode_url: "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
dbeaver_url: "https://dbeaver.io/files/dbeaver-ce-latest-linux.gtk.x86_64.tar.gz"
datagrip_url: "https://download.jetbrains.com/datagrip/datagrip-2024.1.2.tar.gz"
antigravity_url: "https://edgedl.me.gvt1.com/edgedl/release2/j0qc3/antigravity/stable/1.23.2-4781536860569600/linux-x64/Antigravity.tar.gz"
cursor_url: "https://downloads.cursor.com/production/d5b2fc092e16007956c9e5047f76097b9e626cab/linux/x64/Cursor-3.5.17-x86_64.AppImage"
