---
# OS-specific package lists
common_packages_debian:
  - git
  - curl
  - vim
  - tmux
  - htop
  - ufw
  - openssh-server
  - sudo
  - fontconfig

common_packages_fedora:
  - git
  - curl
  - vim-enhanced
  - tmux
  - htop
  - firewalld
  - openssh-server
  - sudo
  - fontconfig

common_packages_alpine:
  - git
  - curl
  - vim
  - tmux
  - htop
  - ufw
  - openssh
  - sudo
  - fontconfig
  - bash
