---
# Docker packages for different distros
docker_packages_debian:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_packages_fedora:
  - container-selinux
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_packages_alpine:
  - docker
  - docker-compose

# Fedora packages that conflict with docker-ce
docker_conflicts_fedora:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux
  - docker-engine-selinux
  - docker-engine
  - moby-engine
