---
virtualization_packages_fedora:
  - "@virtualization"
  - virt-manager
  - libvirt
  - qemu-kvm
  - virt-viewer
  - virt-install
  - bridge-utils
  - libvirt-devel
  - guestfs-tools
  - iptables-services
