---
# tasks file for container-basic

- name: restarting docker daemeon with reaload
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Pull default_container_image docker image 
  docker_image:
    name: "{{ default_container_image }}"
    source: pull
    
- name: Create default_container_name containers
  docker_container:
    name: "{{ default_container_name }}"
    image: "{{ default_container_image }}"
    command: "{{ default_container_command }}"
    state: present

        
