---
- name: Install Dev Tools (Debian)
  package:
    name: "{{ dev_tools_debian }}"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Dev Tools (Fedora)
  package:
    name: "{{ dev_tools_fedora }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Dev Tools (Alpine)
  package:
    name: "{{ dev_tools_alpine }}"
    state: present
  when: ansible_facts['os_family'] == "Alpine"
