---
# This playbook deploys a simple standalone JBoss server.
# https://blog.tomecek.net/post/building-containers-with-buildah-and-ansible/

- hosts: local_machine
  become: yes
  become_method: su
  become_user: root

  vars:
    container_name: "{{ default_container_name }}"
    container_image: "{{ default_container_image }}"

  tasks:    
  - name: Make the base image available
    docker_image:
      name: '{{ container_image }}'



