---
- name: Install virtualization packages (Fedora)
  dnf:
    name: "{{ virtualization_packages_fedora }}"
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Start and enable libvirtd service
  systemd:
    name: libvirtd
    state: started
    enabled: yes
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Add user to libvirt group
  user:
    name: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    groups: libvirt
    append: yes
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Allow Libvirt traffic through iptables (Fix Docker conflict)
  iptables:
    chain: FORWARD
    in_interface: virbr0
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Allow Libvirt traffic outgoing through iptables (Fix Docker conflict)
  iptables:
    chain: FORWARD
    out_interface: virbr0
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Enable NAT for Libvirt (Fix Docker conflict)
  iptables:
    table: nat
    chain: POSTROUTING
    source: 192.168.122.0/24
    destination: "! 192.168.122.0/24"
    jump: MASQUERADE
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Allow Libvirt DHCP traffic (Fix Docker conflict)
  iptables:
    chain: INPUT
    in_interface: virbr0
    protocol: udp
    destination_port: 67
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Allow Libvirt DNS traffic (UDP)
  iptables:
    chain: INPUT
    in_interface: virbr0
    protocol: udp
    destination_port: 53
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Allow Libvirt DNS traffic (TCP)
  iptables:
    chain: INPUT
    in_interface: virbr0
    protocol: tcp
    destination_port: 53
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Ensure iptables-services is installed (to persist rules)
  dnf:
    name: iptables-services
    state: present
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Ensure iptables rules persist
  service:
    name: iptables
    state: started
    enabled: yes
  become: yes
  when: ansible_facts['distribution'] == "Fedora"

- name: Save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables
  become: yes
  when: ansible_facts['distribution'] == "Fedora"
  changed_when: true
