---
- name: Install Azure CLI on Fedora
  dnf:
    name: "{{ azure_cli_package }}"
    state: present
  when: ansible_distribution == "Fedora"

- name: Ensure pip is installed
  dnf:
    name: python3-pip
    state: present

- name: Install all Azure Python requirements from file (Fedora fix)
  pip:
    requirements: "{{ role_path }}/files/requirements-azure.txt"
    state: present
    executable: pip3
    extra_args: "--break-system-packages --pre"

- name: Install Azure Ansible Collection
  command: ansible-galaxy collection install azure.azcollection
  register: collection_install
  changed_when: "'is already installed' not in collection_install.stdout"
