---
# This playbook deploys a simple standalone JBoss server.

- hosts: local_machine
  become: yes
  become_method: su
  become_user: root

  tasks:

  roles:
    - docker_install
    - install_python
    - container-basic



